// Code generated by sqlc. DO NOT EDIT.
// Run: make sqlc

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// User is the database model for the users table
type User struct {
	ID        uuid.UUID    `db:"id"         json:"id"`
	Name      string       `db:"name"        json:"name"`
	Email     string       `db:"email"       json:"email"`
	Role      string       `db:"role"        json:"role"`
	IsActive  bool         `db:"is_active"   json:"is_active"`
	CreatedAt time.Time    `db:"created_at"  json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at"  json:"updated_at"`
}

// UpdateUserNameParams holds parameters for updating a user's name
type UpdateUserNameParams struct {
	ID   uuid.UUID `db:"id"`
	Name string    `db:"name"`
}
