// Code generated by sqlc. DO NOT EDIT.
// Run: make sqlc

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAllUsers = `
SELECT id, name, email, role, is_active, created_at, updated_at
FROM users
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.getAllUsersStmt, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(
			&u.ID, &u.Name, &u.Email,
			&u.Role, &u.IsActive, &u.CreatedAt, &u.UpdatedAt,
		); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	return users, rows.Err()
}

const getUserByID = `
SELECT id, name, email, role, is_active, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var u User
	if err := row.Scan(
		&u.ID, &u.Name, &u.Email,
		&u.Role, &u.IsActive, &u.CreatedAt, &u.UpdatedAt,
	); err != nil {
		return nil, err
	}
	return &u, nil
}

const updateUserName = `
UPDATE users
SET name = $2,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.exec(ctx, q.updateUserNameStmt, updateUserName, arg.ID, arg.Name)
	return err
}

const deactivateUser = `
UPDATE users
SET is_active = false,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deactivateUserStmt, deactivateUser, id)
	return err
}
