// Code generated by sqlc. DO NOT EDIT.
// Run: make sqlc

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

// DBTX is a generic interface for both *sql.DB and *sql.Tx
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// New creates a new Queries instance
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Prepare creates a Queries instance with prepared statements
func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.updateUserResetTokenStmt, err = db.PrepareContext(ctx, updateUserResetToken); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserResetToken: %w", err)
	}
	if q.getUserByResetTokenStmt, err = db.PrepareContext(ctx, getUserByResetToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByResetToken: %w", err)
	}
	return &q, nil
}

// Close closes all prepared statements
func (q *Queries) Close() error {
	stmts := []*sql.Stmt{
		q.getUserByEmailStmt,
		q.getUserByIDStmt,
		q.createUserStmt,
		q.updateUserPasswordStmt,
		q.updateUserResetTokenStmt,
		q.getUserByResetTokenStmt,
	}
	var firstErr error
	for _, s := range stmts {
		if s != nil {
			if err := s.Close(); err != nil && firstErr == nil {
				firstErr = err
			}
		}
	}
	return firstErr
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

// Queries holds prepared statements and implements the raw SQL queries
type Queries struct {
	db                      DBTX
	tx                      *sql.Tx
	getUserByEmailStmt      *sql.Stmt
	getUserByIDStmt         *sql.Stmt
	createUserStmt          *sql.Stmt
	updateUserPasswordStmt  *sql.Stmt
	updateUserResetTokenStmt *sql.Stmt
	getUserByResetTokenStmt *sql.Stmt
}

// WithTx returns a new Queries scoped to a transaction
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                      tx,
		tx:                      tx,
		getUserByEmailStmt:      q.getUserByEmailStmt,
		getUserByIDStmt:         q.getUserByIDStmt,
		createUserStmt:          q.createUserStmt,
		updateUserPasswordStmt:  q.updateUserPasswordStmt,
		updateUserResetTokenStmt: q.updateUserResetTokenStmt,
		getUserByResetTokenStmt: q.getUserByResetTokenStmt,
	}
}
