// Code generated by sqlc. DO NOT EDIT.
// Run: make sqlc

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// User is the database model for the users table
type User struct {
	ID                 uuid.UUID      `db:"id"                   json:"id"`
	Name               string         `db:"name"                 json:"name"`
	Email              string         `db:"email"                json:"email"`
	Password           string         `db:"password"             json:"-"`
	Role               string         `db:"role"                 json:"role"`
	IsActive           bool           `db:"is_active"            json:"is_active"`
	ResetPasswordToken sql.NullString `db:"reset_password_token" json:"-"`
	CreatedAt          time.Time      `db:"created_at"           json:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at"           json:"updated_at"`
}

// CreateUserParams holds parameters for creating a new user
type CreateUserParams struct {
	Email    string    `db:"email"`
	Name     string    `db:"name"`
	Password string    `db:"password"`
	Role     string    `db:"role"`
	IsActive bool      `db:"is_active"`
}

// UpdateUserPasswordParams holds parameters for updating a user password
type UpdateUserPasswordParams struct {
	ID       uuid.UUID `db:"id"`
	Password string    `db:"password"`
}

// UpdateUserResetTokenParams holds parameters for updating a user reset token
type UpdateUserResetTokenParams struct {
	ID                 uuid.UUID      `db:"id"`
	ResetPasswordToken sql.NullString `db:"reset_password_token"`
}

// GetUserByIDRow is the result row for GetUserByID
type GetUserByIDRow struct {
	ID        uuid.UUID    `db:"id"         json:"id"`
	Name      string       `db:"name"        json:"name"`
	Email     string       `db:"email"       json:"email"`
	Role      string       `db:"role"        json:"role"`
	IsActive  bool         `db:"is_active"   json:"is_active"`
	CreatedAt time.Time    `db:"created_at"  json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at"  json:"updated_at"`
}

// GetUserByResetTokenRow is the result row for GetUserByResetToken
type GetUserByResetTokenRow struct {
	ID    uuid.UUID `db:"id"    json:"id"`
	Name  string    `db:"name"  json:"name"`
	Email string    `db:"email" json:"email"`
}
