// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID                 uuid.UUID      `json:"id"`
	Name               string         `json:"name"`
	Email              string         `json:"email"`
	Password           string         `json:"password"`
	Role               string         `json:"role"`
	IsActive           bool           `json:"isActive"`
	ResetPasswordToken sql.NullString `json:"resetPasswordToken"`
	CreatedAt          time.Time      `json:"createdAt"`
	UpdatedAt          sql.NullTime   `json:"updatedAt"`
}
