// Code generated by sqlc. DO NOT EDIT.
// Run: make sqlc

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserByEmail = `
SELECT id, name, email, password, role, is_active, created_at, updated_at
FROM users
WHERE email = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var u User
	if err := row.Scan(
		&u.ID, &u.Name, &u.Email, &u.Password,
		&u.Role, &u.IsActive, &u.CreatedAt, &u.UpdatedAt,
	); err != nil {
		return nil, err
	}
	return &u, nil
}

const getUserByID = `
SELECT id, name, email, role, is_active, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*GetUserByIDRow, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var u GetUserByIDRow
	if err := row.Scan(
		&u.ID, &u.Name, &u.Email,
		&u.Role, &u.IsActive, &u.CreatedAt, &u.UpdatedAt,
	); err != nil {
		return nil, err
	}
	return &u, nil
}

const createUser = `
INSERT INTO users (email, name, password, role, is_active, created_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Email, arg.Name, arg.Password, arg.Role, arg.IsActive,
	)
	var id uuid.UUID
	if err := row.Scan(&id); err != nil {
		return uuid.Nil, err
	}
	return id, nil
}

const updateUserPassword = `
UPDATE users
SET password = $2,
    reset_password_token = null,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.exec(ctx, q.updateUserPasswordStmt, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserResetToken = `
UPDATE users
SET reset_password_token = $2,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserResetToken(ctx context.Context, arg UpdateUserResetTokenParams) error {
	_, err := q.exec(ctx, q.updateUserResetTokenStmt, updateUserResetToken,
		arg.ID, arg.ResetPasswordToken,
	)
	return err
}

const getUserByResetToken = `
SELECT id, name, email
FROM users
WHERE reset_password_token = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetUserByResetToken(ctx context.Context, token sql.NullString) (*GetUserByResetTokenRow, error) {
	row := q.queryRow(ctx, q.getUserByResetTokenStmt, getUserByResetToken, token)
	var u GetUserByResetTokenRow
	if err := row.Scan(&u.ID, &u.Name, &u.Email); err != nil {
		return nil, err
	}
	return &u, nil
}
